# serene v5.2.1
#
# - docs: https://github.com/isunjn/serene/blob/latest/USAGE.md
# - check for updates: https://github.com/isunjn/serene/releases
#
#=========================================================================================

base_url = "https://libremusings.dev"
title = "Libre Musings"
description = "Pondering over FLOSS, code and existence"
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false # Keep this false, as it may cause issues with some styles
build_search_index = false # Keep this false, search is temporarily unsupported
generate_feeds = true # Whether to generate a feed file in root, read docs for more info about rss feed
feed_filenames = ["atom.xml"] # "feed.xml" | "atom.xml" | "rss.xml", read docs for more info
taxonomies = [{ name = "tags" }, { name = "categories" }]
author = "Keerthana Rajesh Kumar"

[markdown]
highlight_code = false
highlight_theme = "css"
extra_syntaxes_and_themes = ["./static/highlight_themes"]
highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]

sections = [
  { name = "About", path = "/about", is_external = false },
  { name = "Articles", path = "/articles", is_external = false },
  { name = "Blog", path = "/blog", is_external = false },
#  { name = "tags", path = "/tags", is_external = false },
  {name = "Photos", path = "https://album.libremusings.dev/?t=bByc5JU5#5Ja1ooNSSHywixy7ZsLgUfUJDQNi5ECvJT7ZgdXpxHr", is_external = true}
]

search = false
blog_section_path = "/blog"

back_link_text = "Back" # Text of the back button
force_theme = "light" # false | "light" | "dark"

footer_copyright = "© 2025 libremusings"
footer_credits = true # Whether to show "Built with zola and serene" in footer

not_found_error_text = "404 Not Found"
not_found_recover_text = "« Return home »"

#reaction = false # Whether to enable anonymous emoji reactions (Note: You need to set up a working api endpoint to enable this feature)
#reaction_align = "right" # "left" | "center" | "right"
#reaction_endpoint = "https://example.com/api/reaction"
